apiVersion: v1
kind: Service
metadata:
  name: charno-frontend
  labels:
    app: charno-frontend
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: charno-frontend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  sessionAffinity: None
