apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: web
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/managed-by: argocd
spec:
  spec:
    encryptedData:
      .dockerconfigjson: AgCzELmE88Jm2+ph2DQhH5vXdqkI0FCBjFMtFOB7Wkc0SuPLiXtB1MxW056KQgMK9Zcn4tAWxtRv2KbeUm/1o+JHiC6WQOHbvudLlClpnhGqFw7AGpIRYW4gxF6d++DJVwT3D/SBZLvyTBRd8K8+L3ZLIJX9ie7cIaL+OUUr6vylnWnR+65Pfx4xg6f5J2/Eha8dLhBPO2ymQfCQIvwiVIbfIa0niQLANDSk2bFLwejKAM0Q+xZwerrhg0Fct23B0kohsGqKRxr1wD23jgDmc0YpGeMgyxfFkDbcEHi2868dEpZZjYTRznRPKx8Zj+oUF1fYlxOqQhBhuUPobcXtgEpq4i+2+2ZArF002lsoaYNiBHu6Y3M0COv6/iRWhKc9mO0weCBZy8WRb8VIh2wtRyJeZqbwVwsqlrWgaVf5FKZSkVadTuVRq/dGG/Bn+A2TxyzL8KIKwBvRtRCBqRWjbUP6a4GVcpEvKSIO8/3EJsrWejIhpJp8ilUXnNvxlDK4an0tenUG68FYgLcXR3k9C69UH7BRQxYJxg0NqRaVqJ7a5PtP5eTjDC0OTtQ4KdsFeAO9SagwTJXBRsmUvBmPz7iyRC+NjT61wlvYBH1SqH8tu6YvmuGlVpguY0rDsOEpDjjJeCVmOFCSuWwH2rn1q6OEwpCMl6aJHen1aLPnsOvcZ+FOEUWVEuaWqikcsQTU7r2tuDr0vKdulwCMpu2z58J8AlDhAX4au/cIYeGZi0lM/A41C52tjiFsBlg2WvQTl5dvs8VP5fWTh4DdxUROFEVAZFaXu6AngEiHPBGDarU75tIRtpjmYUovw6Q5SxobM4r5LKPVEEeRck/41pWeBM+OCctTbbHKlK4dpJ9RAGEcVFDLp1oRLrZsggqTX3mIkzqFw1uYH5AsZ0Gpb/MHM154HemXaoY8cQET39mIxZ8/cC5j2j0xt/v6sAaeNIFl1/TDlqnk2V7d0xrqDkbgpF8sr3i/E8x62RGtXq8Q2UzCMVpPWx1+yvMVLeFfiDkiycBPFID8ukQEdg7yFZCUA8d4IXqVq1byQqgJSDAFJ43SBx1mhn9+Iicik9N2dJOTk5rfnbsug+IeFGAfeFcrXbwj0/UX7bOOlSi3A7IJlp4gAYWQAqqTOxOwLYUAJk1kx6NJgnp3
    template:
      metadata:
        name: ghcr-secret
        namespace: web
      type: kubernetes.io/dockerconfigjson
