apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web

resources:
  - namespace.yaml
  - configmap.yaml
  - secret-template.yaml
  # postgres-configmap.yaml - Removed: Using external Postgres
  # postgres-deployment.yaml - Removed: Using external Postgres
  - photos-pvc.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress-external.yaml
  - ingress-local.yaml
  - lod-ingress-external.yaml
  - lod-ingress-local.yaml

commonLabels:
  app.kubernetes.io/name: web
  app.kubernetes.io/managed-by: argocd

images:
  - name: ghcr.io/mcharno/charno-backend
    newTag: main-bdfdf2aade69d6b94ca245af57afaaca56df8abd
  - name: ghcr.io/mcharno/charno-frontend
    newTag: main-bdfdf2aade69d6b94ca245af57afaaca56df8abd
