apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: charno-web

resources:
  - namespace.yaml
  - configmap.yaml
  - secret-template.yaml
  - postgres-configmap.yaml
  - postgres-deployment.yaml
  - photos-pvc.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: charno-web
  app.kubernetes.io/managed-by: argocd

images:
  - name: ghcr.io/GITHUB_USERNAME/charno-backend
    newTag: latest
  - name: ghcr.io/GITHUB_USERNAME/charno-frontend
    newTag: latest
