apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web

resources:
  - namespace.yaml
  - configmap.yaml
  - secret-template.yaml
  # postgres-configmap.yaml - Removed: Using external Postgres
  # postgres-deployment.yaml - Removed: Using external Postgres
  - photos-pvc.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: web
  app.kubernetes.io/managed-by: argocd

images:
  - name: ghcr.io/mcharno/charno-backend
    newTag: main-ddf033ccdd08ba6e55e5c976fbf48d1e4332b45f
  - name: ghcr.io/mcharno/charno-frontend
    newTag: main-ddf033ccdd08ba6e55e5c976fbf48d1e4332b45f
