apiVersion: v1
kind: Service
metadata:
  name: charno-frontend
  namespace: charno-web
  labels:
    app: charno-frontend
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: charno-frontend
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
